### ISSUE TITLE
Dropdown design bug on the navbar

### ISSUE THREAD

**Issue by shahshivam058** [healthier-ai/healthier-ai.github.io#74]
![Screenshot from 2020-07-31 09-09-08](https://user-images.githubusercontent.com/59441391/88997922-7db15d00-d30e-11ea-84b2-5c6b54adbb4d.png)

you can see the dropdown bug on the program in navbar menu

**Comment by shahshivam058** [comment]
@arps18  Can you check this one bug

**Comment by arps18** [comment]
Hey, @shahshivam058 Can you please elaborate about the bug?

**Comment by shahshivam058** [comment]
@arps18 check drop down icon on program menu  in the navbar i think you can remove this and show all sub menu when hover on program

**Comment by arps18** [comment]
Thanks @shahshivam058 for the thought, but this is a part of the design and the dropdown icon has been added intentionally! Thanks for the concern😁
